// This file is generated by Astro DB
declare module 'astro:db' {
	export const TablaCrm: import("@astrojs/db/runtime").Table<
		"TablaCrm",
		{"calle":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"calle","collection":"TablaCrm","primaryKey":false,"optional":false}},"vendedor":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"vendedor","collection":"TablaCrm","primaryKey":false,"optional":false}},"noticias":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"noticias","collection":"TablaCrm","primaryKey":false,"optional":false}}}
	>;
}
